- name: Bug
  description: Something isn't working right.
  color: '450F08'
- name: Cannot Reproduce
  description: Could not reproduce whatever was going on.
  color: 'B87176'
- name: Chore
  description: A catch-all for things that don't fit another category.
  color: 'C5DEF5'
- name: Dependency
  description: Dependencies need updating.
  color: '707153'
- name: Documentation
  description: Improving documentation.
  color: '4F7AD1'
- name: Duplicate
  description: Something already exists that covers this.
  color: 'B6B4C1'
- name: Feature
  description: A request to add a new feature or functionality.
  color: '517E1C'
- name: Need More Information
  description: There's not enough information to do anything with this.
  color: '9C7509'
- name: Refactor
  description: Related to refactoring code.
  color: '6E89A9'
- name: Release
  description: Related to releasing a new version.
  color: '63FDB7'
- name: Security
  description: Related to security and code exploits.
  color: 'C82E15'
- name: Tech Debt
  description: Something relating to outstanding technical debt.
  color: 'E2AA60'
- name: Will Not Fix
  description: Either not our issue or outside the scope of the project.
  color: 'E5D5F5'
- name: Working As Intended
  description: It's doing what it's supposed to do.
  color: '8F41B2'
