#!/usr/bin/env bash
# shellcheck disable=SC2034
HERE="$(cd "$(dirname "$0")" && pwd)"
# shellcheck disable=SC2016
declare -A EXIT_MESSAGES=(
    [PRE_COMMIT_MISSING]='[ERROR] Could not locate `pre-commit`!'
    [GIT_LFS_MISSING]='[ERROR] This repository is configured for Git LFS but `git-lfs` was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting the relevant parts of the `pre-commit` file in the hooks directory (set by `core.hookspath`; usually `.git/hooks`).'
    [PRE_COMMIT_FAILED]='[ERROR] `pre-commit` failed!'
)
declare -A EXIT_CODES=(
    [PRE_COMMIT_MISSING]=1
    [GIT_LFS_MISSING]=2
    [PRE_COMMIT_FAILED]=3
)
PRE_COMMIT="$(command -v pre-commit)"
if [[ -n "${PRE_COMMIT}" ]]; then
    PYTHON="$(find "$(dirname "${PRE_COMMIT}")" -type f -iregex ".+/python(.exe)?")"
    if [[ -n "${PYTHON}" ]]; then
        "${PYTHON}" -mpre_commit hook-impl --config=.pre-commit-config.yaml --hook-type=pre-commit --skip-on-missing-config --hook-dir "${HERE}" -- "$@"
    else
        "${PRE_COMMIT}" hook-impl --config=.pre-commit-config.yaml --hook-type=pre-commit --skip-on-missing-config --hook-dir "${HERE}" -- "$@"
    fi
    RESULT=$?
else
    # shellcheck disable=SC2059
    printf "${EXIT_MESSAGES[PRE_COMMIT_MISSING]}"
    exit "${EXIT_CODES[PRE_COMMIT_MISSING]}"
fi
if [[ "${RESULT}" -ne 0 ]]; then
    # shellcheck disable=SC2059
    printf "${EXIT_MESSAGES[PRE_COMMIT_FAILED]}"
    exit "${EXIT_CODES[PRE_COMMIT_FAILED]}"
fi
