set(CMAKE_SYSTEM_NAME "Linux" CACHE STRING "" FORCE)
set(CMAKE_SYSTEM_PROCESSOR "x86_64" CACHE STRING "" FORCE)

set(__CLANG_TARGET_TRIPLE "${CMAKE_SYSTEM_PROCESSOR}")

if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    string(APPEND __CLANG_TARGET_TRIPLE "-unknown-linux-gnu")
elseif(CMAKE_SYSTEM_NAME STREQUAL "Windows")
    string(APPEND __CLANG_TARGET_TRIPLE "-pc-windows-gnu")
elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
    string(APPEND __CLANG_TARGET_TRIPLE "-apple-darwin")
else()
    message(FATAL_ERROR "Unsupported system \"${CMAKE_SYSTEM_NAME}\"!")
endif()

set(CLANG_TARGET_TRIPLE "${CMAKE_SYSTEM_PROCESSOR}" CACHE STRING "" FORCE)
unset(__CLANG_TARGET_TRIPLE)

set(CMAKE_C_COMPILER_TARGET "${CLANG_TARGET_TRIPLE}" CACHE STRING "" FORCE)
set(CMAKE_CXX_COMPILER_TARGET "${CLANG_TARGET_TRIPLE}" CACHE STRING "" FORCE)

find_program(CLANG_C_COMPILER_PATH "clang" HINTS "/usr/bin" "/bin" ENV CLANG_PATH ENV CLANG_C_PATH REQUIRED NO_CACHE)
find_program(CLANG_CXX_COMPILER_PATH "clang++" HINTS "/usr/bin" "/bin" ENV CLANG_PATH ENV CLANG_CXX_PATH REQUIRED NO_CACHE)

set(CMAKE_C_COMPILER "${CLANG_C_COMPILER_PATH}" CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER "${CLANG_CXX_COMPILER_PATH}" CACHE FILEPATH "" FORCE)
set(CMAKE_LINKER_TYPE LLD)

unset(CLANG_C_COMPILER_PATH)
unset(CLANG_CXX_COMPILER_PATH)

set(CMAKE_BUILD_TYPE "Debug" CACHE STRING "" FORCE)
set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM "NEVER" CACHE STRING "" FORCE)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY "ONLY" CACHE STRING "" FORCE)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE "ONLY" CACHE STRING "" FORCE)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE "ONLY" CACHE STRING "" FORCE)
