# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build
on:
  push:
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      build-os:
        description: >
          The operating system to build for.

          Valid options are:
           * `linux`
           * `windows`
           * `macos`
        type: string
        required: true
      build-config:
        description: |
          The configuration to build.

          Valid options are:
           * `Release`
           * `Debug`
        type: string
        required: true
    secrets:
      github-token:
        description: |
          The token to use when accessing GitHub APIs.
        required: true
    outputs:
      artifact-id:
        description: |
          The ID of the artifact produced by the build.
        value: ${{jobs.build.outputs.artifact-id}}
      artifact-name:
        description: |
          The name of the artifact produced by the build.
        value: ${{jobs.build.outputs.artifact-name}}
jobs:
  build:
    name: Build
    runs-on: ${{matrix.build-os}}
    strategy:
      fail-fast: true
      matrix:
        build-os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        build-config:
          - Release
          - Debug
        exclude:
          - build-config: ${{(inputs.build-config == 'Release' && 'Debug') || (inputs.build-config == 'Debug' && 'Release')}}
          - build-os: ${{(inputs.build-os == 'linux' && 'windows-latest') || (inputs.build-os == 'macos' && 'windows-latest') || (inputs.build-os == 'windows' && '')}}
          - build-os: ${{(inputs.build-os == 'linux' && '') || (inputs.build-os == 'macos' && 'ubuntu-latest') || (inputs.build-os == 'windows' && 'ubuntu-latest')}}
          - build-os: ${{(inputs.build-os == 'linux' && 'macos-latest') || (inputs.build-os == 'macos' && '') || (inputs.build-os == 'windows' && 'macos-latest')}}
    outputs:
      artifact-id: ${{steps.upload-artifacts.outputs.artifact-id}}
      artifact-name: ${{steps.upload-artifacts.outputs.artifact-name}}
    env:
      NUGET_PACKAGES: ${{github.workspace}}/.nuget/packages
    steps:
      - id: checkout-repository
        name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: glektarssza/glekcraft
          token: ${{secrets.github-token}}
          lfs: true
      - id: setup-dotnet
        name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
          cache: true
          cache-dependency-path: "**/packages.lock.json"
      - id: restore-dependencies
        name: Restore dependencies
        run: dotnet restore --locked-mode
      - id: build
        name: Build
        run: dotnet build --no-restore --configuration ${{matrix.build-config}}
      - id: prepare-artifacts
        name: Prepare artifacts
        run: dotnet publish --no-build --output dist --configuration ${{matrix.build-config}} ./Glekcraft/Glekcraft.csproj
      - id: upload-artifacts
        name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{matrix.build-config}}-${{matrix.build-os}}
          path: dist
