# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: Lint
on:
  workflow_call:
    inputs:
      git-ref:
        description: |
          The Git reference to run the workflow on.

          Must be a valid commit-ish (a branch, tag, commit, etc.).

          Defaults to the reference that triggered the workflow for push and
          pull request events ("github.ref") and the head SHA ("github.sha") for
          all other events.
        type: string
        required: false
        default: ${{github.ref || github.sha || github.event.repository.default_branch}}
    secrets:
      github-token:
        description: |
          The token to use for authentication when making calls to the GitHub
          APIs.

          Defaults to the value in "secrets.GITHUB_TOKEN" if not provided.
        required: false
env:
  GITHUB_TOKEN: ${{secrets.github-token || secrets.GITHUB_TOKEN}}
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      # -- Needed to clone the repository
      contents: read
    steps:
      - id: clone-repository
        name: Clone the repository
        uses: actions/checkout@v7
        with:
          lfs: true
          token: ${{env.GITHUB_TOKEN}}
      - id: prepare-python
        name: Prepare Python
        uses: actions/setup-python@v6
        with:
          python-version: '>=3'
      - id: install-pre-commit
        name: Install pre-commit
        run: ./scripts/install-pre-commit.sh --force
      - id: lint
        name: Lint
        run: |
          pre-commit run --all-files
