# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Manual Workflow
on:
  workflow_dispatch:
    inputs:
      node-version:
        description: |
          The NodeJS version to use.

          Defaults to "latest".
        type: string
        required: false
        default: latest
      package-manager:
        description: |
          The NodeJS package manager to use.

          Defaults to "pnpm".
        type: choice
        required: false
        options:
          - pnpm
          - npm
          - yarn
        default: pnpm
      package-manager-version:
        description: |
          The NodeJS package manager version to use.

          Defaults to "latest".
        type: string
        required: false
        default: latest
      artifact-retention-days:
        description: |
          The duration, in days, to retain artifacts for.

          Defaults to '0' which defaults to the value configured for the
          repository.
        type: number
        required: false
        default: 0
jobs:
  lint:
    name: Lint
    permissions:
      # -- To clone repository
      contents: read
    secrets:
      github-token: ${{secrets.GITHUB_TOKEN}}
    uses: ./.github/workflows/lint.yaml
  spell-check:
    name: Spell Check
    permissions:
      # -- To clone repository
      contents: read
    with:
      node-version: ${{inputs.node-version}}
      package-manager: ${{inputs.package-manager}}
      package-manager-version: ${{inputs.package-manager-version}}
    secrets:
      github-token: ${{secrets.GITHUB_TOKEN}}
    uses: ./.github/workflows/spell-check.yaml
  build:
    name: Build
    permissions:
      # -- To clone repository
      contents: read
    strategy:
      fail-fast: false
      matrix:
        build-os:
          - windows
          - linux
          - macos
        build-config:
          - debug
          - release
    secrets:
      github-token: ${{secrets.GITHUB_TOKEN}}
    uses: ./.github/workflows/build.yaml
    with:
      project: Glekcraft
      build-os: ${{matrix.build-os}}
      build-config: ${{matrix.build-config}}
  test:
    name: Test
    permissions:
      # -- To clone repository
      contents: read
    strategy:
      fail-fast: false
      matrix:
        build-os:
          - windows
          - linux
          - macos
        build-config:
          - debug
          - release
    secrets:
      github-token: ${{secrets.GITHUB_TOKEN}}
      reportgenerator-license: ${{secrets.REPORTGENERATOR_LICENSE}}
    uses: ./.github/workflows/test.yaml
    with:
      build-os: ${{matrix.build-os}}
      build-config: ${{matrix.build-config}}
      upload-artifacts: ${{matrix.build-config == 'debug' && matrix.build-os == 'windows'}}
