# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: On Pull request
on:
  pull_request:
    branches:
      - main
concurrency:
  group: on-pull-request
  cancel-in-progress: true
  queue: single
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  lint:
    name: Lint
    permissions:
      # -- Needed to clone the repository
      contents: read
    uses: ./.github/workflows/lint.yaml
    secrets:
      github-token: ${{secrets.GITHUB_TOKEN}}
  spell-check:
    name: Spell Check
    permissions:
      # -- Needed to clone the repository
      contents: read
    uses: ./.github/workflows/spell-check.yaml
    secrets:
      github-token: ${{secrets.GITHUB_TOKEN}}
  build:
    name: Build
    permissions:
      # -- Needed to clone the repository
      contents: read
    strategy:
      fail-fast: true
      matrix:
        build-os:
          - linux
          - windows
          - osx
        build-config:
          - release
          - debug
    uses: ./.github/workflows/build.yaml
    with:
      build-config: ${{matrix.build-config}}
      build-os: ${{matrix.build-os}}
    secrets:
      github-token: ${{secrets.GITHUB_TOKEN}}
