# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Pull Request
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build
    strategy:
      fail-fast: true
      matrix:
        build-os:
          - windows
          - linux
          - macos
        build-config:
          - debug
          - release
    permissions:
      contents: read
    secrets:
      github-token: ${{secrets.GITHUB_TOKEN}}
    uses: ./.github/workflows/build.yaml
    with:
      build-os: ${{matrix.build-os}}
      build-config: ${{matrix.build-config}}
  test:
    name: Test
    strategy:
      fail-fast: true
      matrix:
        build-os:
          - windows
          - linux
          - macos
    permissions:
      contents: read
    secrets:
      github-token: ${{secrets.GITHUB_TOKEN}}
    uses: ./.github/workflows/test.yaml
    with:
      build-os: ${{matrix.build-os}}
  lint:
    name: Lint
    permissions:
      contents: read
    secrets:
      github-token: ${{secrets.GITHUB_TOKEN}}
    uses: ./.github/workflows/lint.yaml
