# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Test
on:
  workflow_dispatch:
    inputs:
      build-os:
        description: >
          The operating system to build for.

          Valid options are:
           * `windows`
           * `linux`
           * `macos`
        type: choice
        required: true
        options:
          - windows
          - linux
          - macos
  workflow_call:
    inputs:
      build-os:
        description: >
          The operating system to build for.

          Valid options are:
           * `windows`
           * `linux`
           * `macos`
        type: string
        required: true
    secrets:
      github-token:
        description: >
          The token to use for making authenticated GitHub calls.
        required: true
jobs:
  test:
    name: Test
    runs-on: ${{(inputs.build-os == 'windows' && 'windows-latest') || (inputs.build-os == 'macos' && 'macos-latest') || (inputs.build-os == 'linux' && 'ubuntu-latest') || ''}}
    env:
      NUGET_PACKAGES: ${{github.workspace}}/.nuget/packages/
    steps:
      - id: checkout-repository
        name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          token: ${{secrets.github-token || secrets.GITHUB_TOKEN}}
      - id: setup-dotnet
        name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
          cache: true
          cache-dependency-path: '**/packages.lock.json'
      - id: restore-dependencies
        name: Restore dependencies
        run: dotnet restore --locked-mode --use-current-runtime
      - id: test
        name: Test
        run: dotnet test --no-restore --use-current-runtime
